"""Add gateway control-plane persistence (issue #29).

Revision ID: e29a01c7b901
Revises: d4a8c2e67190
"""

from alembic import op
import sqlalchemy as sa

revision = "e29a01c7b901"
down_revision = "d4a8c2e67190"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "perfiles_hardware",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=64), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("activo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "plantillas_pasarela",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("estado", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("estado IN ('draft', 'active', 'retired')", name="ck_plantillas_estado"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "versiones_plantilla_pasarela",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plantilla_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("estado", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column("definicion", sa.JSON(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "estado IN ('draft', 'active', 'retired')", name="ck_versiones_plantilla_estado"
        ),
        sa.CheckConstraint("version > 0", name="ck_versiones_plantilla_version"),
        sa.ForeignKeyConstraint(
            ["plantilla_id"],
            ["plantillas_pasarela.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plantilla_id", "version", name="uq_versiones_plantilla_version"),
    )
    op.create_table(
        "pasarelas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("predio_id", sa.Integer(), nullable=False),
        sa.Column(
            "estado", sa.String(length=24), server_default="pending_activation", nullable=False
        ),
        sa.Column("credencial_hash", sa.CHAR(length=64), nullable=True),
        sa.Column("credencial_prefijo", sa.String(length=16), nullable=True),
        sa.Column("config_version_activa", sa.Integer(), server_default="0", nullable=False),
        sa.Column("bindings_revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column("ultimo_heartbeat_en", sa.DateTime(), nullable=True),
        sa.Column("activado_en", sa.DateTime(), nullable=True),
        sa.Column("revocado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("eliminado_en", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "estado IN ('pending_activation', 'active', 'revoked')", name="ck_pasarelas_estado"
        ),
        sa.CheckConstraint(
            "config_version_activa >= 0 AND bindings_revision >= 0", name="ck_pasarelas_revisions"
        ),
        sa.CheckConstraint(
            "credencial_hash IS NULL OR length(credencial_hash) = 64", name="ck_pasarelas_hash"
        ),
        sa.ForeignKeyConstraint(
            ["predio_id"],
            ["predios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credencial_hash"),
        sa.UniqueConstraint("id", "predio_id", name="uq_pasarelas_id_predio"),
        sa.UniqueConstraint("predio_id"),
    )
    op.create_table(
        "configuraciones_pasarela",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("predio_id", sa.Integer(), nullable=False),
        sa.Column("pasarela_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("version_plantilla_id", sa.Integer(), nullable=True),
        sa.Column("publicado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("publicado_por_usuario_id", sa.Integer(), nullable=True),
        sa.CheckConstraint("version > 0", name="ck_config_version"),
        sa.ForeignKeyConstraint(
            ["pasarela_id", "predio_id"],
            ["pasarelas.id", "pasarelas.predio_id"],
            name="fk_config_gateway_property",
        ),
        sa.ForeignKeyConstraint(
            ["predio_id"],
            ["predios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["publicado_por_usuario_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_plantilla_id"],
            ["versiones_plantilla_pasarela.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("predio_id", "version", name="uq_config_predio_version"),
    )
    op.create_table(
        "referencias_activacion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pasarela_id", sa.Integer(), nullable=False),
        sa.Column("referencia_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("emitido_por_usuario_id", sa.Integer(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("expira_en", sa.DateTime(), nullable=False),
        sa.Column("usado_en", sa.DateTime(), nullable=True),
        sa.Column("invalidado_en", sa.DateTime(), nullable=True),
        sa.Column("resultado", sa.String(length=16), server_default="issued", nullable=False),
        sa.CheckConstraint(
            "resultado IN ('issued', 'consumed', 'revoked')", name="ck_referencias_resultado"
        ),
        sa.CheckConstraint("expira_en > creado_en", name="ck_referencias_expiry"),
        sa.CheckConstraint("length(referencia_hash) = 64", name="ck_referencias_hash"),
        sa.ForeignKeyConstraint(
            ["emitido_por_usuario_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pasarela_id"],
            ["pasarelas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("referencia_hash"),
    )
    op.create_table(
        "ranuras_logicas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pasarela_id", sa.Integer(), nullable=False),
        sa.Column("nodo_id", sa.Integer(), nullable=False),
        sa.Column("area_riego_id", sa.Integer(), nullable=False),
        sa.Column("perfil_hardware_id", sa.Integer(), nullable=True),
        sa.Column("version_plantilla_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["area_riego_id"],
            ["areas_riego.id"],
        ),
        sa.ForeignKeyConstraint(
            ["nodo_id"],
            ["nodos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pasarela_id"],
            ["pasarelas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["perfil_hardware_id"],
            ["perfiles_hardware.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_plantilla_id"],
            ["versiones_plantilla_pasarela.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("area_riego_id"),
        sa.UniqueConstraint(
            "id", "pasarela_id", "nodo_id", "area_riego_id", name="uq_ranuras_identity"
        ),
        sa.UniqueConstraint("nodo_id"),
    )
    op.create_table(
        "vinculos_fisicos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pasarela_id", sa.Integer(), nullable=False),
        sa.Column("ranura_id", sa.Integer(), nullable=False),
        sa.Column("nodo_id", sa.Integer(), nullable=False),
        sa.Column("area_riego_id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(length=128), nullable=False),
        sa.Column("numero_serie", sa.String(length=100), nullable=False),
        sa.Column("estado", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("propuesto_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("confirmado_en", sa.DateTime(), nullable=True),
        sa.Column("cerrado_en", sa.DateTime(), nullable=True),
        sa.Column("confirmado_por_pasarela_id", sa.Integer(), nullable=True),
        sa.Column(
            "nodo_confirmado_id",
            sa.Integer(),
            sa.Computed(
                "CASE WHEN estado = 'confirmed' THEN nodo_id ELSE NULL END", persisted=True
            ),
            nullable=True,
        ),
        sa.Column(
            "uid_confirmado",
            sa.String(length=128),
            sa.Computed("CASE WHEN estado = 'confirmed' THEN uid ELSE NULL END", persisted=True),
            nullable=True,
        ),
        sa.CheckConstraint(
            "estado <> 'closed' OR cerrado_en IS NOT NULL", name="ck_binding_closed"
        ),
        sa.CheckConstraint(
            "estado <> 'confirmed' OR (confirmado_en IS NOT NULL AND confirmado_por_pasarela_id IS NOT NULL AND cerrado_en IS NULL)",
            name="ck_binding_confirmed",
        ),
        sa.CheckConstraint(
            "estado IN ('pending', 'confirmed', 'closed')", name="ck_binding_estado"
        ),
        sa.CheckConstraint(
            "confirmado_por_pasarela_id IS NULL OR confirmado_por_pasarela_id = pasarela_id",
            name="ck_binding_confirming_gateway",
        ),
        sa.ForeignKeyConstraint(
            ["confirmado_por_pasarela_id"],
            ["pasarelas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ranura_id", "pasarela_id", "nodo_id", "area_riego_id"],
            [
                "ranuras_logicas.id",
                "ranuras_logicas.pasarela_id",
                "ranuras_logicas.nodo_id",
                "ranuras_logicas.area_riego_id",
            ],
            name="fk_binding_slot_identity",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nodo_confirmado_id", name="uq_binding_current_node"),
        sa.UniqueConstraint("pasarela_id", "uid_confirmado", name="uq_binding_current_uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Preserve control-plane history; rollback with populated tables is operational.
    connection = op.get_bind()
    if connection.scalar(sa.text("SELECT COUNT(*) FROM vinculos_fisicos")):
        raise RuntimeError("Refusing downgrade: vinculos_fisicos contains gateway history")
    if connection.scalar(sa.text("SELECT COUNT(*) FROM ranuras_logicas")):
        raise RuntimeError("Refusing downgrade: ranuras_logicas contains gateway history")
    if connection.scalar(sa.text("SELECT COUNT(*) FROM referencias_activacion")):
        raise RuntimeError("Refusing downgrade: referencias_activacion contains gateway history")
    if connection.scalar(sa.text("SELECT COUNT(*) FROM configuraciones_pasarela")):
        raise RuntimeError("Refusing downgrade: configuraciones_pasarela contains gateway history")
    if connection.scalar(sa.text("SELECT COUNT(*) FROM pasarelas")):
        raise RuntimeError("Refusing downgrade: pasarelas contains gateway history")
    if connection.scalar(sa.text("SELECT COUNT(*) FROM versiones_plantilla_pasarela")):
        raise RuntimeError(
            "Refusing downgrade: versiones_plantilla_pasarela contains gateway history"
        )
    if connection.scalar(sa.text("SELECT COUNT(*) FROM plantillas_pasarela")):
        raise RuntimeError("Refusing downgrade: plantillas_pasarela contains gateway history")
    if connection.scalar(sa.text("SELECT COUNT(*) FROM perfiles_hardware")):
        raise RuntimeError("Refusing downgrade: perfiles_hardware contains gateway history")
    op.drop_table("vinculos_fisicos")
    op.drop_table("ranuras_logicas")
    op.drop_table("referencias_activacion")
    op.drop_table("configuraciones_pasarela")
    op.drop_table("pasarelas")
    op.drop_table("versiones_plantilla_pasarela")
    op.drop_table("plantillas_pasarela")
    op.drop_table("perfiles_hardware")
